name: zju health report script
on:
  schedule:
    # Beijing time 0:30
    - cron:  '0 0 * * *'

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        env: # Or as an environment variable
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          province: ${{ secrets.province }}
          city: ${{ secrets.city }}
          county: ${{ secrets.county }} 
        with:
          args: "chrome xx.js"
